### ISSUE TITLE
Getting started tutorial

### ISSUE THREAD

**Issue by SmallProgramIndustry** [Pragmatists/microfrontends#3]
Can explain how the project is used and how to build it, it is best to have a tutorial, thank you

**Comment by internettrans** [comment]
Hi @SmallProgramIndustry, this project uses [single-spa](https://single-spa.js.org/) to structure the microfrontends. I'd suggest checking out [this recommended setup](https://single-spa.js.org/docs/recommended-setup) and [these examples](https://single-spa.js.org/docs/examples).
